### PR TITLE
More robust views and fix for issue #2.

### PR DESCRIPTION
**Pull request by peterjaric**
Fixes problem discussed in pull request https://github.com/digitalfreedom/website/pull/7#issuecomment-137689081 and fixes bug with old content (issue #2).
Country code changed to country name in popups.

### CODE REVIEW

**Comment by peterjaric** [comment]
I merged the recent changes into my fork, to make this pull request easier to merge.

**Comment by botherder** [comment]
Hey Peter, thanks for this! There are still some merge conflicts due to another pull request that refactored a bit the code. Would you be able to resolve the conflicts?

**Comment by peterjaric** [comment]
Now merged. Also made the modal dialog open the correct tab corresponding to the current active package. 

I renamed the npm build command from watch to watch_dev, and then added a new watch command that doesn't load the dev config. Hopefully that was OK. As far as I understand it, the dev config assumes you have a host named dev serving the packages, which may not be true for everyone.

Plus some small refactorings.

**Comment by botherder** [comment]
Thank you Peter.

**Pull request merged**
